DROP TABLE quotes IF EXISTS;
DROP TABLE vehicles IF EXISTS;
DROP TABLE drivers IF EXISTS;

CREATE TABLE drivers (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name        VARCHAR(30),
  last_name         VARCHAR_IGNORECASE(30),
  address           VARCHAR(255),
  city              VARCHAR(80),
  postal_code       VARCHAR(10),
  telephone         VARCHAR(20),
  date_of_birth     DATE,
  license_years_held INTEGER
);
CREATE INDEX drivers_last_name ON drivers (last_name);

CREATE TABLE vehicles (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_year      INTEGER,
  make            VARCHAR(50),
  model           VARCHAR(50),
  usage_type      VARCHAR(20),
  annual_mileage  INTEGER,
  driver_id       INTEGER NOT NULL
);
ALTER TABLE vehicles ADD CONSTRAINT fk_vehicles_drivers FOREIGN KEY (driver_id) REFERENCES drivers (id);
CREATE INDEX vehicles_driver_id ON vehicles (driver_id);

CREATE TABLE quotes (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id           INTEGER NOT NULL,
  vehicle_id          INTEGER NOT NULL,
  liability_limit     VARCHAR(20),
  deductible          VARCHAR(20),
  base_rate           DECIMAL(10, 2),
  age_factor          DECIMAL(6, 3),
  vehicle_age_factor  DECIMAL(6, 3),
  usage_factor        DECIMAL(6, 3),
  coverage_factor     DECIMAL(6, 3),
  annual_premium      DECIMAL(10, 2),
  created_at          TIMESTAMP
);
ALTER TABLE quotes ADD CONSTRAINT fk_quotes_drivers FOREIGN KEY (driver_id) REFERENCES drivers (id);
ALTER TABLE quotes ADD CONSTRAINT fk_quotes_vehicles FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);
CREATE INDEX quotes_driver_id ON quotes (driver_id);
